services:
  - type: web
    name: flipko-store
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server_py.py
    envVars:
      - key: PORT
        value: 3000
      - key: PYTHON_VERSION
        value: 3.11.0
